name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://partners.doctolib.fr/booking/la-salle-des-greniers-saint-jean-centre-de-vaccination.json | jq . > la-salle-des-greniers-saint-jean-centre-de-vaccination.json
        curl https://partners.doctolib.fr/booking/centre-de-vaccination-covid-de-versailles.json | jq . > centre-de-vaccination-covid-de-versailles.json
        start_date=$(date +%Y-%m-%d -d "+10 days")
        curl "https://partners.doctolib.fr/availabilities.json?start_date=${start_date}&visit_motive_ids=2547915&agenda_ids=419043&insurance_sector=public&practice_ids=164517&destroy_temporary=true&limit=15&allowNewPatients=true&telehealth=false&profileId=242564&isOrganization=true&telehealthFeatureEnabled=false&vaccinationMotive=true&vaccinationDaysRange=26&vaccinationCenter=true&nbConfirmedVaccinationAppointments=4435" | jq . > la-salle-des-greniers-saint-jean-centre-de-vaccination.availabilities.2547915.json
        curl "https://partners.doctolib.fr/availabilities.json?start_date=${start_date}&visit_motive_ids=2532017&agenda_ids=412038&insurance_sector=public&practice_ids=165155&destroy_temporary=true&limit=7&allowNewPatients=true&telehealth=false&profileId=243206&isOrganization=true&telehealthFeatureEnabled=false&vaccinationMotive=true&vaccinationDaysRange=26&vaccinationCenter=true&nbConfirmedVaccinationAppointments=917" | jq . > centre-de-vaccination-covid-19-de-rambouillet.availabilities.2532017.json
        curl "https://partners.doctolib.fr/availabilities.json?start_date=${start_date}&visit_motive_ids=2532017&agenda_ids=412033-413610-413611-412034&insurance_sector=public&practice_ids=165154&destroy_temporary=true&limit=7&allowNewPatients=true&telehealth=false&profileId=243464&isOrganization=true&telehealthFeatureEnabled=false&vaccinationMotive=true&vaccinationDaysRange=26&vaccinationCenter=true&nbConfirmedVaccinationAppointments=3343" | jq . > centre-de-vaccination-covid-19-de-montigny-le-bretonneux.availabilities.2532017.json
        curl "https://partners.doctolib.fr/availabilities.json?start_date=${start_date}&visit_motive_ids=2551694&agenda_ids=411755-411756&insurance_sector=public&practice_ids=165067&destroy_temporary=true&limit=7&allowNewPatients=true&telehealth=false&profileId=243226&isOrganization=true&telehealthFeatureEnabled=false&vaccinationMotive=true&vaccinationDaysRange=26&vaccinationCenter=true&nbConfirmedVaccinationAppointments=19624" | jq . > centre-de-vaccination-covid-19-du-var.availabilities.2551694.json
        sed -i -r 's/\"number_future_vaccinations\"\:\s*[0-9]+/\"number_future_vaccinations\"\:\"ignored\"/' *.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
