name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        start_date=$(date +%Y-%m-%d -d "+10 days")
        curl https://partners.doctolib.fr/booking/la-salle-des-greniers-saint-jean-centre-de-vaccination.json | jq . > la-salle-des-greniers-saint-jean-centre-de-vaccination.json
        sed -i -r 's/\"number_future_vaccinations\"\:[0-9]+/\"number_future_vaccinations\"\:\"ignored\"/' la-salle-des-greniers-saint-jean-centre-de-vaccination.json
        curl "https://partners.doctolib.fr/availabilities.json?start_date=${start_date}&visit_motive_ids=2547915&agenda_ids=419043&insurance_sector=public&practice_ids=164517&destroy_temporary=true&limit=15&allowNewPatients=true&telehealth=false&profileId=242564&isOrganization=true&telehealthFeatureEnabled=false&vaccinationMotive=true&vaccinationDaysRange=26&vaccinationCenter=true&nbConfirmedVaccinationAppointments=4435" | jq . > availabilities.2547915.json
        sed -i -r 's/\"number_future_vaccinations\"\:[0-9]+/\"number_future_vaccinations\"\:\"ignored\"/' availabilities.2547915.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
